name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Sjekk ut koden fra repositoryet
      - name: Check out the code
        uses: actions/checkout@v2

      # Sett opp Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Sett opp SAM CLI
      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam-cli@v1

      # Konfigurer AWS-legitimasjonene for GitHub Actions
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # Bygg SAM-applikasjonen
      - name: Build SAM Application
        run: sam build

      # Deploy SAM-applikasjonen
      - name: Deploy SAM Application
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name image-generator-lambda-29 \
            --s3-bucket pgr301-couch-explorers \
            --capabilities CAPABILITY_IAM \
            --region eu-west-1
